In [1]:
from google.colab import files
uploaded = files.upload()

Saving Heart_Disease_Prediction.csv to Heart_Disease_Prediction.csv

Import Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)

Load Dataset

In [3]:
df = pd.read_csv("Heart_Disease_Prediction.csv")
df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

Explore Dataset

In [4]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease            270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

Encode Target

In [5]:
encoder = LabelEncoder()
df["Heart Disease"] = encoder.fit_transform(df["Heart Disease"])

Features & Target

In [6]:
X = df.drop("Heart Disease", axis=1)
y = df["Heart Disease"]

Train/Test Split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Task 1 — Logistic Regression

In [8]:
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print("Accuracy:")
print(accuracy_score(y_test, lr_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, lr_pred))

print("\nClassification Report")
print(classification_report(y_test, lr_pred))

Accuracy:
0.9259259259259259

Confusion Matrix
[[32  1]
 [ 3 18]]

Classification Report
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        33
           1       0.95      0.86      0.90        21

    accuracy                           0.93        54
   macro avg       0.93      0.91      0.92        54
weighted avg       0.93      0.93      0.93        54

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Task 2 — KNN

In [9]:
knn_scores = {}

for k in [3,5,7]:

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(X_train,y_train)

    pred = model.predict(X_test)

    acc = accuracy_score(y_test,pred)

    knn_scores[k]=acc

    print(f"\nK = {k}")
    print("Accuracy =",acc)

K = 3
Accuracy = 0.6666666666666666

K = 5
Accuracy = 0.6481481481481481

K = 7
Accuracy = 0.6851851851851852

Find Best K

In [10]:
best_k = max(knn_scores,key=knn_scores.get)
print("Best K =",best_k)

Best K = 7

Train Final KNN

In [11]:
knn = KNeighborsClassifier(n_neighbors=best_k)

knn.fit(X_train,y_train)

knn_pred = knn.predict(X_test)

print(confusion_matrix(y_test,knn_pred))

print(classification_report(y_test,knn_pred))

[[24  9]
 [ 8 13]]
              precision    recall  f1-score   support

           0       0.75      0.73      0.74        33
           1       0.59      0.62      0.60        21

    accuracy                           0.69        54
   macro avg       0.67      0.67      0.67        54
weighted avg       0.69      0.69      0.69        54

Task 3 — Decision Tree

In [12]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train,y_train)

dt_pred = dt.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,dt_pred))

print("\nConfusion Matrix")

print(confusion_matrix(y_test,dt_pred))

print("\nClassification Report")

print(classification_report(y_test,dt_pred))

Accuracy
0.6851851851851852

Confusion Matrix
[[22 11]
 [ 6 15]]

Classification Report
              precision    recall  f1-score   support

           0       0.79      0.67      0.72        33
           1       0.58      0.71      0.64        21

    accuracy                           0.69        54
   macro avg       0.68      0.69      0.68        54
weighted avg       0.70      0.69      0.69        54

Task 4 — Comparison Table

In [13]:
comparison = pd.DataFrame({

"Model":[
"Logistic Regression",
"KNN",
"Decision Tree"
],

"Accuracy":[
accuracy_score(y_test,lr_pred),
accuracy_score(y_test,knn_pred),
accuracy_score(y_test,dt_pred)
],

"Precision":[
precision_score(y_test,lr_pred),
precision_score(y_test,knn_pred),
precision_score(y_test,dt_pred)
],

"Recall":[
recall_score(y_test,lr_pred),
recall_score(y_test,knn_pred),
recall_score(y_test,dt_pred)
],

"F1 Score":[
f1_score(y_test,lr_pred),
f1_score(y_test,knn_pred),
f1_score(y_test,dt_pred)
]

})

comparison

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.925926   0.947368  0.857143  0.900000
1                  KNN  0.685185   0.590909  0.619048  0.604651
2        Decision Tree  0.685185   0.576923  0.714286  0.638298

Task 5 — Predict 5 New Samples

In [14]:
new_data = pd.DataFrame([
[45,1,2,130,230,0,2,150,0,1.0,2,0,3],
[60,0,4,145,280,1,0,120,1,2.5,2,2,7],
[55,1,3,135,250,0,2,160,0,0.5,1,0,3],
[67,1,4,160,300,1,0,110,1,3.0,3,3,7],
[39,0,2,120,190,0,2,170,0,0.0,1,0,3]
], columns=X.columns)

Predictions

In [15]:
print("Logistic Regression")
print(encoder.inverse_transform(lr.predict(new_data)))

print()

print("KNN")
print(encoder.inverse_transform(knn.predict(new_data)))

print()

print("Decision Tree")
print(encoder.inverse_transform(dt.predict(new_data)))

Logistic Regression
['Absence' 'Presence' 'Absence' 'Presence' 'Absence']

KNN
['Absence' 'Presence' 'Absence' 'Presence' 'Absence']

Decision Tree
['Absence' 'Presence' 'Absence' 'Presence' 'Absence']

Task 6 — Best Model

In [16]:
models = {

"Logistic Regression":accuracy_score(y_test,lr_pred),

"KNN":accuracy_score(y_test,knn_pred),

"Decision Tree":accuracy_score(y_test,dt_pred)

}

best_model = max(models,key=models.get)

print("Best Model :",best_model)

print("Best Accuracy :",models[best_model])

Best Model : Logistic Regression
Best Accuracy : 0.9259259259259259

Why I selected this model:                                               
I selected this model because it achieved the highest accuracy on the test dataset. It also provided better precision, recall, and F1-score than the other models, making it the most reliable classifier for predicting heart disease in this dataset.